server_base_url: "http://localhost:5953"
server_live_url: "http://localhost:5953"
server_port: "5953"
server_api_key: "asdf"
server_cookie_secret: "asdf="
server_cookie_secret_message: "why"
admin_username: "asdf"
admin_password: "asdf"
time_zone: "America/New_York"
bolt_db_path: "./bolt.db"
bolt_db_encryption_key: "asdf"
redis_host: "localhost"
redis_port: "6379"
redis_db_number: 1
redis_password: ""
serve_directory: "./public"
serve_browsable: true
serve_index_file: "./index.html"
public_limiter_max: 1
public_limiter_seconds: 1
public_limiter_max_limit_count: 3